### ISSUE TITLE
Free Space does not fit

### ISSUE THREAD

**Issue by taurec76** [betonme/e2openplugin-InfoBarTunerState#13]
I noticed that the free space in recording list is higher than checking freespace with df directly on box.
If I change line 869 from:

self.freespace = int ( ( stat.f_bfree / 1000 * stat.f_bsize / 1000 ) / 1024 )
to:
self.freespace = int ( ( stat.f_bavail / 1024 * stat.f_frsize / 1024 ) / 1024 )

then the free space from df is equal to plugin view.

**Comment by betonme** [comment]
Thanks. I fixed it

**Comment by taurec76** [comment]
Thanks, but I guess you update only the numbers but not the changed properties which causes the wrong free space numbers

**Comment by betonme** [comment]
Yes, You're right
